In [87]:
import pandas as pd
import numpy as np

In [88]:
df = pd.read_csv('vgsales.csv')

In [3]:
df2 = df.set_index('Platform')
df2

,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Platform,,,,,,,,,
Wii,Wii Sports,2006.0,1,Nintendo,41.49,29.02,3.77,8.46,82.74
NES,Super Mario Bros.,1985.0,2,Nintendo,29.08,3.58,6.81,0.77,40.24
Wii,Mario Kart Wii,2008.0,3,Nintendo,15.85,12.88,3.79,3.31,35.82
Wii,Wii Sports Resort,2009.0,1,Nintendo,15.75,11.01,3.28,2.96,33.00
GB,Pokemon Red/Pokemon Blue,1996.0,4,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...
GBA,Woody Woodpecker in Crazy Castle 5,2002.0,2,Kemco,0.01,0.00,0.00,0.00,0.01
GC,Men in Black II: Alien Escape,2003.0,7,Infogrames,0.01,0.00,0.00,0.00,0.01
PS2,SCORE International Baja 1000: The Official Game,2008.0,3,Activision,0.00,0.00,0.00,0.00,0.01
DS,Know How 2,2010.0,5,7G//AMES,0.00,0.01,0.00,0.00,0.01
GBA,Spirits & Spells,2003.0,2,Wanadoo,0.01,0.00,0.00,0.00,0.01

In [9]:
df2.loc['PS4']

,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Platform,,,,,,,,,
PS4,Call of Duty: Black Ops 3,2015.0,7,Activision,5.77,5.81,0.35,2.31,14.24
PS4,Grand Theft Auto V,2014.0,9,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98
PS4,FIFA 16,2015.0,1,Electronic Arts,1.11,6.06,0.06,1.26,8.49
PS4,Star Wars Battlefront (2015),2015.0,7,Electronic Arts,2.93,3.29,0.22,1.23,7.67
PS4,Call of Duty: Advanced Warfare,2014.0,7,Activision,2.80,3.30,0.14,1.37,7.60
...,...,...,...,...,...,...,...,...,...
PS4,Dynasty Warriors: Eiketsuden,2016.0,9,Tecmo Koei,0.00,0.00,0.01,0.00,0.01
PS4,Paragon,2016.0,9,Epic Games,0.01,0.00,0.00,0.00,0.01
PS4,Chaos;Child,2015.0,11,5pb,0.00,0.00,0.01,0.00,0.01
PS4,God Eater Off Shot: Tachibana Sakuya-hen Twin ...,2016.0,9,Namco Bandai Games,0.00,0.00,0.01,0.00,0.01
PS4,Farming 2017 - The Simulation,2016.0,8,UIG Entertainment,0.00,0.01,0.00,0.00,0.01

In [19]:
x = df2.loc['PS4'].sort_values('Global_Sales', ascending = False).head(10)
x

,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Platform,,,,,,,,,
PS4,Call of Duty: Black Ops 3,2015.0,7,Activision,5.77,5.81,0.35,2.31,14.24
PS4,Grand Theft Auto V,2014.0,9,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98
PS4,FIFA 16,2015.0,1,Electronic Arts,1.11,6.06,0.06,1.26,8.49
PS4,Star Wars Battlefront (2015),2015.0,7,Electronic Arts,2.93,3.29,0.22,1.23,7.67
PS4,Call of Duty: Advanced Warfare,2014.0,7,Activision,2.80,3.30,0.14,1.37,7.60
PS4,Fallout 4,2015.0,4,Bethesda Softworks,2.47,3.15,0.24,1.10,6.96
PS4,FIFA 15,2014.0,1,Electronic Arts,0.79,4.29,0.05,1.47,6.59
PS4,Destiny,2014.0,7,Activision,2.49,2.05,0.16,0.96,5.65
PS4,FIFA 17,2016.0,1,Electronic Arts,0.28,3.75,0.06,0.69,4.77
PS4,The Last of Us,2014.0,9,Sony Computer Entertainment,1.78,1.87,0.07,0.82,4.55

In [8]:
df2.loc['PS4'].max()

Name            inFAMOUS: Second Son
Year                          2017.0
Genre                             12
Publisher                       Yeti
NA_Sales                        5.77
EU_Sales                        6.06
JP_Sales                        0.48
Other_Sales                     2.31
Global_Sales                   14.24
dtype: object

In [31]:
x['JP_Sales_EU_Sales'] = x['JP_Sales'] + x['EU_Sales']
x['JP_Sales_EU_Sales']

Platform
PS4    6.16
PS4    6.17
PS4    6.12
PS4    3.51
PS4    3.44
PS4    3.39
PS4    4.34
PS4    2.21
PS4    3.81
PS4    1.94
Name: JP_Sales_EU_Sales, dtype: float64

In [41]:
x

,Name,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales,JP_Sales+EU_Sales
Platform,,,,,,,,,,
PS4,Call of Duty: Black Ops 3,2015.0,7,Activision,5.77,5.81,0.35,2.31,14.24,6.16
PS4,Grand Theft Auto V,2014.0,9,Take-Two Interactive,3.80,5.81,0.36,2.02,11.98,6.17
PS4,FIFA 16,2015.0,1,Electronic Arts,1.11,6.06,0.06,1.26,8.49,6.12
PS4,Star Wars Battlefront (2015),2015.0,7,Electronic Arts,2.93,3.29,0.22,1.23,7.67,3.51
PS4,Call of Duty: Advanced Warfare,2014.0,7,Activision,2.80,3.30,0.14,1.37,7.60,3.44
PS4,Fallout 4,2015.0,4,Bethesda Softworks,2.47,3.15,0.24,1.10,6.96,3.39
PS4,FIFA 15,2014.0,1,Electronic Arts,0.79,4.29,0.05,1.47,6.59,4.34
PS4,Destiny,2014.0,7,Activision,2.49,2.05,0.16,0.96,5.65,2.21
PS4,FIFA 17,2016.0,1,Electronic Arts,0.28,3.75,0.06,0.69,4.77,3.81
PS4,The Last of Us,2014.0,9,Sony Computer Entertainment,1.78,1.87,0.07,0.82,4.55,1.94

In [61]:
df

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
0,Wii Sports,Wii,2006.0,1,Nintendo,41.49,29.02,3.77,8.46,82.74
1,Super Mario Bros.,NES,1985.0,2,Nintendo,29.08,3.58,6.81,0.77,40.24
2,Mario Kart Wii,Wii,2008.0,3,Nintendo,15.85,12.88,3.79,3.31,35.82
3,Wii Sports Resort,Wii,2009.0,1,Nintendo,15.75,11.01,3.28,2.96,33.00
4,Pokemon Red/Pokemon Blue,GB,1996.0,4,Nintendo,11.27,8.89,10.22,1.00,31.37
...,...,...,...,...,...,...,...,...,...,...
16593,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,2,Kemco,0.01,0.00,0.00,0.00,0.01
16594,Men in Black II: Alien Escape,GC,2003.0,7,Infogrames,0.01,0.00,0.00,0.00,0.01
16595,SCORE International Baja 1000: The Official Game,PS2,2008.0,3,Activision,0.00,0.00,0.00,0.00,0.01
16596,Know How 2,DS,2010.0,5,7G//AMES,0.00,0.01,0.00,0.00,0.01
16597,Spirits & Spells,GBA,2003.0,2,Wanadoo,0.01,0.00,0.00,0.00,0.01

# exercise 6

In [84]:
#How many games were released for XOne in 2016? Which was the top selling in Europe?
df.groupby('Year').count()

,Name,Platform,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
Year,,,,,,,,,
1980.0,9,9,9,9,9,9,9,9,9
1981.0,46,46,46,46,46,46,46,46,46
1982.0,36,36,36,36,36,36,36,36,36
1983.0,17,17,17,17,17,17,17,17,17
1984.0,14,14,14,14,14,14,14,14,14
1985.0,14,14,14,14,14,14,14,14,14
1986.0,21,21,21,21,21,21,21,21,21
1987.0,16,16,16,16,16,16,16,16,16
1988.0,15,15,15,15,15,15,15,15,15
1989.0,17,17,17,17,17,17,17,17,17
1990.0,16,16,16,16,16,16,16,16,16
1991.0,41,41,41,41,41,41,41,41,41
1992.0,43,43,43,43,43,43,43,43,43
1993.0,60,60,60,60,60,60,60,60,60
1994.0,121,121,121,121,121,121,121,121,121
1995.0,219,219,219,219,219,219,219,219,219
1996.0,263,263,263,263,263,263,263,263,263
1997.0,289,289,289,289,289,289,289,289,289
1998.0,379,379,379,379,379,379,379,379,379
1999.0,338,338,338,338,338,338,338,338,338
2000.0,349,349,349,349,349,349,349,349,349
2001.0,482,482,482,482,482,482,482,482,482
2002.0,829,829,829,829,829,829,829,829,829
2003.0,775,775,775,775,775,775,775,775,775
2004.0,763,763,763,744,763,763,763,763,763
2005.0,941,941,941,936,941,941,941,941,941
2006.0,1008,1008,1008,1008,1008,1008,1008,1008,1008
2007.0,1202,1202,1202,1201,1202,1202,1202,1202,1202
2008.0,1428,1428,1428,1428,1428,1428,1428,1428,1428
2009.0,1431,1431,1431,1431,1431,1431,1431,1431,1431
2010.0,1259,1259,1259,1257,1259,1259,1259,1259,1259
2011.0,1139,1139,1139,1136,1139,1139,1139,1139,1139
2012.0,657,657,657,655,657,657,657,657,657
2013.0,527,527,527,527,527,527,527,527,527
2014.0,521,521,521,519,521,521,521,521,521
2015.0,535,535,535,535,535,535,535,535,535
2016.0,503,503,503,501,503,503,503,503,503
2017.0,3,3,3,3,3,3,3,3,3
2020.0,1,1,1,1,1,1,1,1,1

In [97]:
df.loc[(df['Platform']== 'XOne') & (df['Year']==2016.0)]

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
845,Tom Clancy's The Division,XOne,2016.0,7,Ubisoft,1.20,0.62,0.00,0.18,2.01
1224,FIFA 17,XOne,2016.0,1,Electronic Arts,0.17,1.26,0.00,0.10,1.53
2434,Far Cry: Primal,XOne,2016.0,9,Ubisoft,0.46,0.32,0.00,0.07,0.85
2444,Overwatch,XOne,2016.0,7,Activision,0.52,0.25,0.00,0.08,0.85
2505,Madden NFL 17,XOne,2016.0,1,Electronic Arts,0.72,0.02,0.00,0.09,0.82
2991,Doom (2016),XOne,2016.0,7,Bethesda Softworks,0.39,0.23,0.00,0.06,0.68
3145,NBA 2K17,XOne,2016.0,1,Take-Two Interactive,0.54,0.04,0.00,0.07,0.64
3927,Quantum Break,XOne,2016.0,9,Microsoft Game Studios,0.27,0.19,0.01,0.04,0.51
4430,Plants vs. Zombies: Garden Warfare 2,XOne,2016.0,7,Electronic Arts,0.26,0.15,0.00,0.04,0.44
4820,EA Sports UFC 2,XOne,2016.0,1,Electronic Arts,0.23,0.14,0.00,0.04,0.40
5015,Forza Horizon 3,XOne,2016.0,3,Microsoft Game Studios,0.15,0.20,0.00,0.03,0.38
5268,Dark Souls III,XOne,2016.0,4,Namco Bandai Games,0.23,0.09,0.00,0.03,0.35
5595,LEGO Marvel's Avengers,XOne,2016.0,9,Warner Bros. Interactive Entertainment,0.18,0.11,0.00,0.03,0.32
6157,Naruto Shippuden: Ultimate Ninja Storm 4,XOne,2016.0,10,Namco Bandai Games,0.19,0.06,0.00,0.03,0.28
6910,Lego Star Wars: The Force Awakens,XOne,2016.0,9,Warner Bros. Interactive Entertainment,0.12,0.10,0.00,0.02,0.24
8751,NHL 17,XOne,2016.0,1,Electronic Arts,0.13,0.01,0.00,0.02,0.15
8860,Mirror's Edge Catalyst,XOne,2016.0,2,Electronic Arts,0.08,0.05,0.00,0.02,0.15
8947,Deus Ex: Mankind Divided,XOne,2016.0,4,Square Enix,0.08,0.06,0.00,0.01,0.15
9646,Battleborn,XOne,2016.0,7,Take-Two Interactive,0.08,0.04,0.00,0.01,0.13
9700,Homefront: The Revolution,XOne,2016.0,7,Deep Silver,0.05,0.07,0.00,0.01,0.12
9711,Rocket League,XOne,2016.0,1,505 Games,0.03,0.09,0.00,0.01,0.12
10038,DiRT Rally,XOne,2016.0,3,Codemasters,0.03,0.08,0.00,0.01,0.11
10047,Life is Strange,XOne,2016.0,11,Square Enix,0.08,0.02,0.00,0.01,0.11
10814,ReCore,XOne,2016.0,9,Microsoft Game Studios,0.06,0.03,0.00,0.01,0.10
11140,F1 2016 (Codemasters),XOne,2016.0,3,Codemasters,0.01,0.07,0.00,0.01,0.09
11550,BioShock The Collection,XOne,2016.0,7,Take-Two Interactive,0.03,0.04,0.00,0.01,0.08
11803,Resident Evil Zero,XOne,2016.0,9,Capcom,0.05,0.02,0.00,0.01,0.07
12579,TrackMania Turbo,XOne,2016.0,9,Ubisoft,0.02,0.03,0.00,0.00,0.06
13174,MXGP 2,XOne,2016.0,3,Milestone S.r.l.,0.02,0.02,0.00,0.00,0.05
13490,Dead Island Definitive Collection,XOne,2016.0,9,Deep Silver,0.02,0.02,0.00,0.00,0.04
13529,R.B.I. Baseball 2016,XOne,2016.0,1,MLB.com,0.04,0.00,0.00,0.00,0.04
13650,7 Days to Die,XOne,2016.0,9,Telltale Games,0.02,0.02,0.00,0.00,0.04
13763,One Piece: Burning Blood,XOne,2016.0,10,Namco Bandai Games,0.03,0.01,0.00,0.00,0.04
13871,Song of the Deep,XOne,2016.0,9,Insomniac Games,0.03,0.00,0.00,0.00,0.04
13950,Resident Evil 6,XOne,2016.0,7,Capcom,0.03,0.00,0.00,0.00,0.04
13994,Destiny: The Collection,XOne,2016.0,7,Activision,0.01,0.02,0.00,0.00,0.04
14186,Teenage Mutant Ninja Turtles: Mutants in Manha...,XOne,2016.0,9,Activision,0.02,0.01,0.00,0.00,0.03
14609,Attack on Titan (KOEI),XOne,2016.0,9,Tecmo Koei,0.01,0.01,0.00,0.00,0.03
14738,Pro Evolution Soccer 2017,XOne,2016.0,1,Konami Digital Entertainment,0.00,0.02,0.00,0.00,0.03
14913,Ghostbusters (2016),XOne,2016.0,9,Activision,0.02,0.00,0.00,0.00,0.02
15052,NASCAR Heat Evolution,XOne,2016.0,3,Dusenberry Martin Racing,0.02,0.00,0.00,0.00,0.02
15203,Valentino Rossi: The Game,XOne,2016.0,3,Namco Bandai Games,0.00,0.02,0.00,0.00,0.02
15341,The Technomancer,XOne,2016.0,4,Focus Home Interactive,0.01,0.01,0.00,0.00,0.02
15720,Arslan: The Warriors of Legend,XOne,2016.0,9,Tecmo Koei,0.01,0.00,0.00,0.00,0.02
15801,XCOM 2,XOne,2016.0,12,Take-Two Interactive,0.01,0.01,0.00,0.00,0.02
16222,Carmageddon: Max Damage,XOne,2016.0,9,Stainless Games,0.01,0.01,0.00,0.00,0.01
16276,Assetto Corsa,XOne,2016.0,3,505 Games,0.00,0.01,0.00,0.00,0.01
16429,Goat Simulator,XOne,2016.0,8,Koch Media,0.00,0.01,0.00,0.00,0.01
16448,Assassin's Creed Chronicles,XOne,2016.0,9,Ubisoft,0.00,0.01,0.00,0.00,0.01
16530,SÃ©bastien Loeb Rally Evo,XOne,2016.0,3,Milestone S.r.l,0.00,0.01,0.00,0.00,0.01
16531,Hitman (2016),XOne,2016.0,9,Square Enix,0.00,0.01,0.00,0.00,0.01
16562,Mighty No. 9,XOne,2016.0,2,Deep Silver,0.01,0.00,0.00,0.00,0.01
16569,Resident Evil 4 HD,XOne,2016.0,7,Capcom,0.01,0.00,0.00,0.00,0.01
16576,Rugby Challenge 3,XOne,2016.0,1,Alternative Software,0.00,0.01,0.00,0.00,0.01

In [100]:
#df.loc[(df['Platform']== 'XOne') & (df['Year']==2016.0)]

df.loc[(df['Platform']== 'XOne') & (df['Year']==2016.0)]['Name'].count()

54

In [101]:
df.loc[(df['Platform']== 'XOne') & (df['Year']==2016.0)].count()

Name            54
Platform        54
Year            54
Genre           54
Publisher       54
NA_Sales        54
EU_Sales        54
JP_Sales        54
Other_Sales     54
Global_Sales    54
dtype: int64

# exercise 7

In [105]:
df['Platform'] = df['Platform'].replace('XOne', 'X Box One')

In [108]:
df.loc[(df['Platform']=='X Box One')]

,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
101,Call of Duty: Black Ops 3,X Box One,2015.0,7,Activision,4.52,2.09,0.01,0.67,7.30
193,Call of Duty: Advanced Warfare,X Box One,2014.0,7,Activision,3.21,1.53,0.01,0.38,5.13
197,Grand Theft Auto V,X Box One,2014.0,9,Take-Two Interactive,2.66,2.01,0.00,0.41,5.08
260,Halo 5: Guardians,X Box One,2015.0,7,Microsoft Game Studios,2.64,1.20,0.03,0.39,4.26
287,Fallout 4,X Box One,2015.0,4,Bethesda Softworks,2.45,1.26,0.01,0.37,4.09
...,...,...,...,...,...,...,...,...,...,...
16530,SÃ©bastien Loeb Rally Evo,X Box One,2016.0,3,Milestone S.r.l,0.00,0.01,0.00,0.00,0.01
16531,Hitman (2016),X Box One,2016.0,9,Square Enix,0.00,0.01,0.00,0.00,0.01
16562,Mighty No. 9,X Box One,2016.0,2,Deep Silver,0.01,0.00,0.00,0.00,0.01
16569,Resident Evil 4 HD,X Box One,2016.0,7,Capcom,0.01,0.00,0.00,0.00,0.01
16576,Rugby Challenge 3,X Box One,2016.0,1,Alternative Software,0.00,0.01,0.00,0.00,0.01

# How many PC games have higher sales than 3 million global sales?
exercise 8

In [111]:
pc_games = df.loc[(df['Platform']=='PC') & (df['Global_Sales'] > 3.0)]['Name'].count()

print('the number of PC games that have higher sales than 3 million global sales are:', pc_games)

the number of PC games that have higher sales than 3 million global sales are: 12